[tool.poetry]
name = "yamlbundler"
version = "0.1.0"
description = ""
authors = ["dr666m1 <skndr666m1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
