on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'
          cache: poetry
      - run: poetry install
      - run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'
      - name: publish
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: make publish
