on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'
          cache: poetry
      - run: poetry install
      - run: make test
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.11'
      - name: build
        run: poetry build
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: ./dist
      - name: publish
        run: poetry publish --username dr666m1 --password "$PYPI_PASSWORD"
        if: ${{ github.ref_type == 'tag' }}
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
